### ISSUE TITLE
Попытка чтения файла без тегов приводит к ошибке

### ISSUE THREAD

**Issue by vpolikarpov** [vladertel/tg_dj#27]
```
Traceback (most recent call last):
  File "/usr/local/tg_dj/run.py", line 59, in <module>
    brain = DjBrain(config, *modules)
  File "/usr/local/tg_dj/brain/DJ_Brain.py", line 58, in __init__
    self.scheduler = Scheduler(config)
  File "/usr/local/tg_dj/brain/scheduler.py", line 47, in __init__
    self.populate_backlog()
  File "/usr/local/tg_dj/brain/scheduler.py", line 77, in populate_backlog
    title, artist, duration = get_mp3_info(file_path)
ValueError: not enough values to unpack (expected 3, got 2)
```

**Comment by vpolikarpov** [comment]
Вот тут https://github.com/vladertel/tg_dj/blob/master/utils.py#L20 в случае отсутствия тегов функция get_mp3_info возвращает два значения вместо трёх, из-за чего и возникает ошибка
